name: ilnitsky-polls-infra

services:
  
  seq:
    image: datalust/seq:2025.2
    container_name: polls-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINUSERNAME=${SEQ_USER}
      - SEQ_FIRSTRUN_ADMINPASSWORD=${SEQ_PASSWORD}
    volumes:
      - seq-data:/data
    ports:
      - "8007:80"
      #- "5341:5341"  # Не выставляем порт наружу из сети
    networks:
      - polls-network

  loki:
    image: grafana/loki:3.5.10
    container_name: polls-loki
    user: "0:0"       # Запуск от имени root (UID 0) чтобы не падал из-за отсутствия прав на создание папки
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/tmp/loki
    #ports:
      #- "3100:3100"  # Не выставляем порт наружу из сети
    networks:
      - polls-network

  prometheus:
    image: prom/prometheus:v3.9.1
    container_name: polls-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    volumes:
      - ./prometheus-config.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9097:9090"
    networks:
      - polls-network

  grafana:
    image: grafana/grafana:12.3
    container_name: polls-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=${GRAFANA_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana-datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
    ports:
      - "3007:3000"
    networks:
      - polls-network
    depends_on:
      - loki
      - prometheus

volumes:
  seq-data:  
  loki-data:
  prometheus-data:
  grafana-data:

networks:
  polls-network:
    name: polls-network   # Явно задаём имя новой сети, чтобы compose не сгенерировал его сам
    driver: bridge
