# Настройка зоны кэша
# keys_zone=nginx_static_cache:10m — 10 МБ под ключи, max_size=512m — лимит данных на диске
proxy_cache_path /var/cache/nginx/proxy_cache levels=1:2 keys_zone=nginx_static_cache:10m max_size=512m inactive=60m use_temp_path=off;


# Внутренний DNS Docker
# Обязателен, чтобы Nginx находил контейнеры по именам сервисов уже после запуска (в момент использования переменной)
resolver 127.0.0.11 valid=30s;

# Блок для перехвата HTTP (порт 80)
server {
    listen 80;											# Слушаем HTTP
    server_name localhost;

    return 301 https://$host$request_uri;				# Редирект. Всё, что пришло на HTTP, уходит на HTTPS
}

# Основной блок для HTTPS (порт 443)
server {
    listen 443 ssl;										# Слушаем HTTPS, включаем шифрование SSL/TLS
    http2 on;											# Активируем поддержку протокола HTTP/2 для всего сервера
    server_name localhost;								# Домен

    ssl_certificate     /etc/nginx/certs/fullchain.pem;	# Путь к файлу публичного сертификата внутри контейнера Nginx
    ssl_certificate_key /etc/nginx/certs/privkey.pem;	# Путь к файлу закрытого ключа

    # Кэшируем все запросы к папке assets
    location /assets/ {
        set $upstream_app http://app:8080;
        proxy_pass $upstream_app;
        
        include proxy_cache_params.conf; # Выносим общие настройки кэша в файл proxy_cache_params.conf

        # Кэширование самим браузером
        add_header Cache-Control "public, max-age=31536000, immutable"; # Браузер сохранит файл на 1 год (31 536 000 секунд) и не будет переспрашивать сервер (immutable)
    }

    # Кэшируем отдельные файлы в корне (favicon, логотипы, манифесты)
    location ~* \.(ico|png|jpg|jpeg|gif|svg|woff|woff2|ttf|eot|json|webmanifest)$ {
        set $upstream_app http://app:8080;
        proxy_pass $upstream_app;

        include proxy_cache_params.conf; # Выносим общие настройки кэша в файл proxy_cache_params.conf

        # Кэширование самим браузером
        add_header Cache-Control "public, max-age=86400, must-revalidate"; # Кэшируем в браузере на 1 день (86 400 секунд). Если файл изменится на сервере, через сутки браузер обновит его сам
    }

    # Приложение
    location / {
        # Используем переменную, чтобы Nginx не падал при старте, если app еще не запущен
        set $upstream_app http://app:8080;

        proxy_pass         $upstream_app;				# Проброс запроса на внутренний порт 8080

        proxy_http_version 1.1;							# Используем HTTP/1.1 вместо 1.0 (обязательно для работы WebSockets/SignalR и стабильного проксирования)

        # Заголовки для работы WebSockets и SignalR
        proxy_set_header   Upgrade $http_upgrade;		# Нужно для WebSockets
        proxy_set_header   Connection keep-alive;		# Нужно для WebSockets

        # Передача данных о клиенте (чтобы UseHttpsRedirection в приложении не зациклился)
        proxy_set_header   Host $host;					# Передаём приложению оригинальный домен
        proxy_set_header   X-Real-IP $remote_addr;		# Передаём приложению реальный IP-адрес клиента
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;	# Передаем цепочку IP-адресов (клиент + все прокси, через которые он прошел)
        proxy_set_header   X-Forwarded-Proto $scheme;	# Передаём приложению оригинальный протокол (http или https)

        proxy_cache_bypass $http_upgrade;				# Исключаем запросы обновления (WebSockets) из кэширования, чтобы они шли напрямую к приложению
    }

    # Grafana
    location /grafana/ {
        proxy_pass         http://grafana:3000;			# Без слеша в конце, если GF_SERVER_SERVE_FROM_SUB_PATH=true
        proxy_set_header   Host $host;
    }

    # Seq
    location /seq/ {
        proxy_pass         http://seq:80/;				# Со слешем в конце
        proxy_set_header   Host $host;
    }
}
