proxy_cache nginx_static_cache;									# Активируем использование зоны кэша с именем 'nginx_static_cache' (которую мы объявили в proxy_cache_path)
proxy_cache_valid 200 60m;										# Задаем время хранения кэша (60 минут) только для успешных ответов с HTTP-статусом 200
proxy_cache_key "$host$request_uri";							# Определяем формат ключа, по которому Nginx будет отличать один файл от другого в своем хранилище

proxy_ignore_headers Cache-Control Expires Set-Cookie;			# Заставляем Nginx кэшировать файлы, даже если ASP.NET прислал заголовки, запрещающие это

add_header X-Proxy-Cache $upstream_cache_status;				# Добавляем в ответ сервера заголовок, который показывает статус кэша:
                                                                # MISS (файл взят из приложения и сохранен в кэш Nginx), 
                                                                # HIT (файл взят из кэша Nginx),
                                                                # BYPASS (кэш проигнорирован, например, для WebSockets)

# Стандартные заголовки проксирования
proxy_set_header Host $host;									# Передаем приложению оригинальный домен из запроса клиента (необходим для корректной генерации ссылок внутри ASP.NET)
proxy_set_header X-Real-IP $remote_addr;						# Передаем приложению IP-адрес клиента (без этого приложение будет видеть только IP-адрес самого Nginx)
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;	# Передаем цепочку IP-адресов всех прокси, через которые прошел запрос, чтобы приложение знало реальный путь клиента
proxy_set_header X-Forwarded-Proto $scheme;						# Сообщаем приложению, какой протокол использовал клиент (http или https), чтобы избежать бесконечных редиректов
