// <auto-generated />
using System;
using Ilnitsky.Polls.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ilnitsky.Polls.DataAccess.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201191721_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.Respondent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("Respondents");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MultipleAnswersCount")
                        .HasColumnType("int");

                    b.Property<Guid?>("MultipleAnswersId")
                        .HasColumnType("UUID");

                    b.Property<Guid>("PollId")
                        .HasColumnType("UUID(36)");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("UUID(36)");

                    b.Property<Guid>("RespondentId")
                        .HasColumnType("UUID(36)");

                    b.Property<Guid>("RespondentSessionId")
                        .HasColumnType("UUID(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("RespondentId");

                    b.HasIndex("RespondentSessionId");

                    b.ToTable("RespondentAnswers");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<string>("AcceptLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsMobile")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Platform")
                        .HasColumnType("longtext");

                    b.Property<string>("RemoteIpAddress")
                        .HasColumnType("longtext");

                    b.Property<Guid>("RespondentId")
                        .HasColumnType("UUID(36)");

                    b.Property<string>("UserAgent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("RespondentId");

                    b.ToTable("RespondentSessions");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Answer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("UUID(36)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Poll", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Html")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Polls");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("UUID");

                    b.Property<bool>("AllowCustomAnswer")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("AllowMultipleChoice")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("DefaultNextNumber")
                        .HasColumnType("int");

                    b.Property<int?>("MatchNextNumber")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<Guid>("PollId")
                        .HasColumnType("UUID(36)");

                    b.Property<string>("TargetAnswer")
                        .HasColumnType("longtext");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PollId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentAnswer", b =>
                {
                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Polls.Poll", "Poll")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Polls.Question", "Question")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Answers.Respondent", "Respondent")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentSession", "RespondentSession")
                        .WithMany("RespondentAnswers")
                        .HasForeignKey("RespondentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");

                    b.Navigation("Question");

                    b.Navigation("Respondent");

                    b.Navigation("RespondentSession");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentSession", b =>
                {
                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Answers.Respondent", "Respondent")
                        .WithMany("RespondentSessions")
                        .HasForeignKey("RespondentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Respondent");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Answer", b =>
                {
                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Polls.Question", "Question")
                        .WithMany("Answers")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Question", b =>
                {
                    b.HasOne("Ilnitsky.Polls.DataAccess.Entities.Polls.Poll", "Poll")
                        .WithMany("Questions")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poll");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.Respondent", b =>
                {
                    b.Navigation("RespondentAnswers");

                    b.Navigation("RespondentSessions");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Answers.RespondentSession", b =>
                {
                    b.Navigation("RespondentAnswers");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Poll", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("RespondentAnswers");
                });

            modelBuilder.Entity("Ilnitsky.Polls.DataAccess.Entities.Polls.Question", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("RespondentAnswers");
                });
#pragma warning restore 612, 618
        }
    }
}
