name: Docker Build and Publish

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  packages: write
  checks: write

jobs:
  build-app:
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем код в рабочую директорию GitHub Actions runner'а
        uses: actions/checkout@v4

      - name: Устанавливаем .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Восстанавливаем NuGet-пакеты из кэша
        uses: actions/cache@v4
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Скачиваем и устанавливаем недостающие NuGet-пакеты
        run: dotnet restore Ilnitsky.Polls.Mono3L.sln

      - name: Сборка решения
        run: dotnet build Ilnitsky.Polls.Mono3L.sln --no-restore --configuration Release

      - name: Сохраняем собранное решение (bin и obj папки)
        uses: actions/upload-artifact@v4
        with:
          name: compiled-app
          path: |
            ./
            !./.git
            !**/node_modules
          retention-days: 1

  run-smoke-tests:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий, чтобы dorny/test-reporter имел доступ к хэшам коммитов git-а
        uses: actions/checkout@v4

      - name: Устанавливаем .NET SDK и настраиваем окружение для запуска тестов
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Запуск тестов Smoke
        run: |
          dotnet test Ilnitsky.Polls.Tests.Smoke/Ilnitsky.Polls.Tests.Smoke.csproj \
          --configuration Release \
          --filter "Category!=LocalOnly" \
          --verbosity normal \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=smoke-test-results.trx" \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*Tests*]*"

      - name: Загружаем результаты тестов как артефакты
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: smoke-test-results-${{ github.run_number }}
          path: '**/TestResults/*.trx'
          retention-days: 7

      - name: Публикуем отчёт в GitHub Pages
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Smoke Tests Results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Удаляем дубликты отчетов покрытия (папки созданные VSTest), чтобы остались только папки созданные Coverlet
        if: always()
        run: rm -rf ./TestResults/_* 

      - name: Сохраняем артефакты отчёта по покрытию Smoke
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-smoke # Имя должно начинаться с coverage-
          path: '**/TestResults/**/coverage.cobertura.xml'
          retention-days: 1

  run-xunit-tests:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий, чтобы dorny/test-reporter имел доступ к хэшам коммитов git-а
        uses: actions/checkout@v4

      - name: Устанавливаем .NET SDK и настраиваем окружение для запуска тестов
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
          cache: true
          cache-dependency-path: '**/*.csproj'

      - name: Запуск тестов xUnit
        run: |
          dotnet test Ilnitsky.Polls.Tests.XUnit/Ilnitsky.Polls.Tests.XUnit.csproj \
          --configuration Release \
          --verbosity normal \
          --collect:"XPlat Code Coverage" \
          --results-directory ./TestResults \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=xunit-test-results.trx" \
          -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Exclude="[*Tests*]*"

      - name: Загружаем результаты тестов как артефакты
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: xunit-test-results-${{ github.run_number }}
          path: '**/TestResults/*.trx'
          retention-days: 7

      - name: Публикуем отчёт по тестам в GitHub Pages
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: xUnit Tests Results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

      - name: Удаляем дубликты отчетов покрытия (папки созданные VSTest), чтобы остались только папки созданные Coverlet
        if: always()
        run: rm -rf ./TestResults/_* 

      - name: Сохраняем артефакты отчёта по покрытию XUnit
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-xunit # Имя должно начинаться с coverage-
          path: '**/TestResults/**/coverage.cobertura.xml'
          retention-days: 1

  run-nunit-tests:
    needs: build-app
    runs-on: ubuntu-latest
    steps:
      - name: Клонируем репозиторий, чтобы dorny/test-reporter имел доступ к хэшам коммитов git-а
        uses: actions/checkout@v4

      - name: Скачиваем уже собранное решение
        uses: actions/download-artifact@v4
        with:
          name: compiled-app

      - name: Устанавливаем .NET SDK и настраиваем окружение для запуска тестов
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Запуск тестов NUnit
        run: |
          dotnet test Ilnitsky.Polls.Tests.NUnit/Ilnitsky.Polls.Tests.NUnit.csproj \
          --no-build \
          --configuration Release \
          --verbosity normal \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=nunit-test-results.trx"

      - name: Загружаем результаты тестов как артефакты
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: nunit-test-results-${{ github.run_number }}
          path: '**/TestResults/*.trx'
          retention-days: 7

      - name: Публикуем отчёт в GitHub Pages
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: NUnit Tests Results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

  run-fluent-tests:
    needs: build-app
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false  # Не отменять другие тесты, если один упал
      matrix:           # matrix создаёт две параллельные копии этой джобы
        test-type: [FluentNUnit, FluentXUnit]
        include:
          - test-type: FluentNUnit
            project: "Ilnitsky.Polls.Tests.NUnit.Fluent/Ilnitsky.Polls.Tests.NUnit.Fluent.csproj"
          - test-type: FluentXUnit
            project: "Ilnitsky.Polls.Tests.XUnit.Fluent/Ilnitsky.Polls.Tests.XUnit.Fluent.csproj"
    steps:
      - name: Клонируем репозиторий, чтобы dorny/test-reporter имел доступ к хэшам коммитов git-а
        uses: actions/checkout@v4

      - name: Скачиваем уже собранное решение
        uses: actions/download-artifact@v4
        with:
          name: compiled-app

      - name: Устанавливаем .NET SDK и настраиваем окружение для запуска тестов
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Запуск тестов ${{ matrix.test-type }}
        run: |
          dotnet test ${{ matrix.project }} \
          --no-build \
          --configuration Release \
          --verbosity normal \
          --logger "console;verbosity=detailed" \
          --logger "trx;LogFileName=${{ matrix.test-type }}-test-results.trx"

      - name: Загружаем результаты тестов как артефакты
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ${{ matrix.test-type }}-test-results-${{ github.run_number }}
          path: '**/TestResults/*.trx'
          retention-days: 7

      - name: Публикуем отчёт в GitHub Pages
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: ${{ matrix.test-type }} Tests Results
          path: '**/TestResults/*.trx'
          reporter: dotnet-trx

  report-coverage:
    needs: [run-xunit-tests, run-smoke-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Скачиваем все артефакты, начинающиеся на coverage-
        uses: actions/download-artifact@v4
        with:
          pattern: coverage-*
          path: merged-coverage/

      - name: Устанавливаем .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Устанавливаем ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Объединяем отчёты о покрытии
        run: |
          reportgenerator \
            -reports:"merged-coverage/**/*.xml" \
            -targetdir:"merged-reports" \
            -reporttypes:"Cobertura;MarkdownSummaryGitHub"

      - name: Создаем краткую таблицу c помощью CodeCoverageSummary
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: 'merged-reports/Cobertura.xml' # Берем объединенный файл
          badge: true
          format: markdown
          output: both
          thresholds: '40 75'

      - name: Выводим Summary
        run: |
          # Для отладки смотрим содержимое папки
          if [ -d "./merged-reports" ]; then
            ls -R ./merged-reports
          else
            echo "Директория merged-reports не найдена!"
            exit 1
          fi
          # Сначала выводим короткую таблицу от CodeCoverageSummary
          if [ -f code-coverage-results.md ]; then
            cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
          fi
          # Затем добавляем подробный отчет от ReportGenerator
          if [ -f merged-reports/SummaryGithub.md ]; then
            cat merged-reports/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
          else
            echo "Итоговый отчет не сформирован" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi

      - name: Сохраняем объединённый отчёт о покрытии
        uses: actions/upload-artifact@v4
        with:
          name: final-coverage-report
          path: merged-reports/

  build-image-and-push:
    runs-on: ubuntu-latest
    needs: [run-xunit-tests, run-nunit-tests, run-fluent-tests, run-smoke-tests]
    steps:
      - name: Клонируем код в рабочую директорию GitHub Actions runner'а
        uses: actions/checkout@v4

      - name: Собираем docker-образ
        run: docker build -f Ilnitsky.Polls/Dockerfile -t polls .

      - name: Входим в GHCR
        if: github.event_name == 'push'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Отправляем образ в GHCR с тегом 'latest'
        if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/'))
        run: |
          # Получаем официальное имя образа для GitHub в нижнем регистре
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          # Присваиваем образу имя и тег
          docker tag polls $IMAGE_NAME:latest
          # Отправляем в GHCR
          docker push $IMAGE_NAME:latest

      - name: Отправляем образ в GHCR с тегом 'хэш-коммита'
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          # Получаем официальное имя образа для GitHub в нижнем регистре
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          # Присваиваем образу имя и тег
          docker tag polls $IMAGE_NAME:${{ github.sha }}
          # Отправляем в GHCR
          docker push $IMAGE_NAME:${{ github.sha }}

      - name: Отправляем образ в GHCR с тегом версии
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          # Получаем официальное имя образа для GitHub в нижнем регистре
          IMAGE_NAME=$(echo "ghcr.io/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          # Присваиваем образу имя и тег
          docker tag polls $IMAGE_NAME:${{ github.ref_name }}
          # Отправляем в GHCR
          docker push $IMAGE_NAME:${{ github.ref_name }}
